<h2>Lets play! <?php echo $this->page->title; ?></h2>
<?php 
//Zend_Debug::dump($this->selected_scrum);
?>


<div>
  <span style="background-color:gainsboro;">&nbsp;Not Started</span>&nbsp;
  <span style="background-color:#D2E0E6;">&nbsp;Started</span>&nbsp;
  <span style="background-color:lightsalmon;">&nbsp;Delayed</span>&nbsp;
  <span style="background-color: lightcoral;">&nbsp;Problem</span>&nbsp;
  <span style="background-color:lightgreen;">&nbsp;Completed</span>&nbsp;
  <span style="background-color:greenyellow;">&nbsp;Anything else</span>&nbsp;
  <br/>  
</div>
<table  id="datatable" class="table table-condensed table-bordered">
  <thead>
      <tr>
         <?php
    echo '<th>' . $this->translate("id_play") . '</th>
    <th>' . $this->translate("fk_id_scrum_item") . '</th>
    <th>' . $this->translate("label") . '</th>
    <th>' . $this->translate("started_on") . '</th>
    <th>' . $this->translate("stopped_on") . '</th>
    <th>' . $this->translate("stop_reason") . '</th>
    <th>' . $this->translate("estimate_duration") . '</th>
    <th>' . $this->translate("estimate_finish") . '</th>
    <th>' . $this->translate("deadline") . '</th>
    <th>' . $this->translate("finished_on") . '</th>
    <th>' . $this->translate("result") . '</th>
    <th>' . $this->translate("result_comment") . '</th>
    <th>' . $this->translate("fk_id_category") . '</th>
    <th>' . $this->translate("fk_id_player") . '</th>
    <th>' . $this->translate("fk_id_team") . '</th>
    <th></th>';?> 
          
      </tr>
  </thead>
  <tbody>

    <?php
    
    
    
    
    foreach ($this->data as $key => $val) {
 
      if($val['fk_id_scrum_item'] == $this->selected_scrum || $this->selected_scrum == null){
      
      
      if($val['started_on']== '0000-00-00 00:00:00'){
      
        $style = "background-color:gainsboro;";
      }else{
        $style = "background-color:#D2E0E6;";
      }
      
      if($val['stopped_on']== '0000-00-00 00:00:00'){
      }else{
        $style = "background-color:lightsalmon;";
      }
      
      if($val['finished_on']== '0000-00-00 00:00:00'){
      }else{
        $style = "background-color:lightgreen;";
      }
      
      
      ;?>
    
      <tr style="<?php echo $style ?>">
        <td><a href="<?php echo $this->baseUrl();?>/play/update/id_play/<?php echo $val['id_play'];?>"><i class="icon-wrench"></i></a></td>
        <td><a href="<?php echo $this->baseUrl();?>/play/list/selected_scrum/<?php echo $val['fk_id_scrum_item'];?>"><?php echo $val['ScrumItem']['label'];?></a></td>
        <td><?php echo $val['label'];?></td>
        <td><?php echo $val['started_on'];?></td>
        
        
        <?php if($val['started_on']!== '0000-00-00 00:00:00'){ ;?>
        <td><?php echo $val['stopped_on'];?></td>
        <td><?php echo $val['stop_reason'];?></td>
        <td><?php echo $val['estimate_duration'];?></td>
        <td><?php echo $val['estimate_finish'];?></td>
        <td><?php echo $val['deadline'];?></td>
        <td><?php echo $val['finished_on'];?></td>
        <td><?php echo $val['result'];?></td>
        <td><?php echo $val['result_comment'];?></td>
        <td><?php echo $val['Category']['label'];?></td>
        <td><?php echo $val['Player']['name'];?></td>
        <td><?php echo $val['Team']['label'];?></td>
        <?php }else{ ;?>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td><?php echo $val['Category']['label'];?></td>
        <td><?php echo $val['Player']['name'];?></td>
        <td><?php echo $val['Team']['label'];?></td>
        <?php } ;?>
        <td><a href="<?php echo $this->baseUrl();?>/play/delete/id_play/<?php echo $val['id_play'];?>"><i class="icon-remove"></i></a></td>
      </tr>
<?php 
      }
      
      }


    ;
    ?>
  </tbody>
  <tfoot>
    <tr>
      <td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td>
    </tr>
  </tfoot>
</table>
<a href="<?php echo $this->baseUrl(); ?>/play/add">Add</a>
