<?php

/**
 * Play
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Play extends Base_Play
{
static public function getAll() {

  $q = Doctrine_Query::create()
            
            ->from("Play pl, pl.ScrumItem sc,pl.Player pp,pl.Team pt,pl.Category pc")
            //->from("StaffStaff ss,ss.StaffIndividual si")
            ->fetchArray();
  
  return $q;
  }
}