<?php

/**
 * ScrumItemTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ScrumItemTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ScrumItemTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ScrumItem');
    }
}