<?php

/**
 * ShortplayTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ShortplayTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ShortplayTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Shortplay');
    }
}