<?php

/**
 * TeamHasPlayerTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TeamHasPlayerTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TeamHasPlayerTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TeamHasPlayer');
    }
}